In [1]:
import numpy as np

In [5]:
array1=np.array([1,2,3,4,5])

In [6]:
array2=np.array([
    [1,2,3,4,5],
    [6,7,8,9,0]
])

In [7]:
print(array1)

[1 2 3 4 5]


In [8]:
print(array2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [11]:
array3=np.array([[
    [11,22,33,44,55],
    [66,77,88,99,00],
    [11,33,55,77,99]
],
      [
          [11,22,33,44,55],
          [66,77,88,99,00],
          [11,33,55,77,99]
      ]])

In [12]:
print(array3)

[[[11 22 33 44 55]
  [66 77 88 99  0]
  [11 33 55 77 99]]

 [[11 22 33 44 55]
  [66 77 88 99  0]
  [11 33 55 77 99]]]


In [21]:
array4=np.zeros((3,5,4))

In [22]:
print(array4)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [23]:
array5=np.ones((3,5,4))
print(array5)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [27]:
array6=np.arange(1,12)
print(array6)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [30]:
array7=np.linspace(1,10,79)
print(array7)

[ 1.          1.11538462  1.23076923  1.34615385  1.46153846  1.57692308
  1.69230769  1.80769231  1.92307692  2.03846154  2.15384615  2.26923077
  2.38461538  2.5         2.61538462  2.73076923  2.84615385  2.96153846
  3.07692308  3.19230769  3.30769231  3.42307692  3.53846154  3.65384615
  3.76923077  3.88461538  4.          4.11538462  4.23076923  4.34615385
  4.46153846  4.57692308  4.69230769  4.80769231  4.92307692  5.03846154
  5.15384615  5.26923077  5.38461538  5.5         5.61538462  5.73076923
  5.84615385  5.96153846  6.07692308  6.19230769  6.30769231  6.42307692
  6.53846154  6.65384615  6.76923077  6.88461538  7.          7.11538462
  7.23076923  7.34615385  7.46153846  7.57692308  7.69230769  7.80769231
  7.92307692  8.03846154  8.15384615  8.26923077  8.38461538  8.5
  8.61538462  8.73076923  8.84615385  8.96153846  9.07692308  9.19230769
  9.30769231  9.42307692  9.53846154  9.65384615  9.76923077  9.88461538
 10.        ]


In [31]:
array3.size

30

In [32]:
array3.shape

(2, 3, 5)

In [33]:
array3.ndim

3

In [34]:
array7.ndim

1

In [35]:
array7.shape

(79,)

In [38]:
array7.dtype

dtype('float64')

In [42]:


list1 = [1, 2, 3, 4, 5]

arraylist = np.array(list1)
print(arraylist)

NameError: name 'list1' is not defined

In [43]:
array2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18,  0]])

In [47]:
array2[1]

array([6, 7, 8, 9, 0])

In [48]:
array2[1,2]

np.int64(8)