In [1]:
import numpy as np

In [2]:
array=np.array([1,2,3,4,5]) #creating array

In [3]:
array1=np.array([           #2D array
    [1,2,3,4,5],
    [6,7,8,9,0]
])

In [4]:
print(array1)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [5]:
print(array1)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [6]:
array2=np.array([[        #3D array
    [11,22,33,44,55],
    [66,77,88,99,00],
    [11,33,55,77,99]
],
      [
          [11,22,33,44,55],
          [66,77,88,99,00],
          [11,33,55,77,99]
      ]])

In [7]:
print(array2)

[[[11 22 33 44 55]
  [66 77 88 99  0]
  [11 33 55 77 99]]

 [[11 22 33 44 55]
  [66 77 88 99  0]
  [11 33 55 77 99]]]


In [8]:
array.ndim

1

In [9]:
array1.ndim

2

In [10]:
array2.ndim

3

In [11]:
array.shape

(5,)

In [12]:
array1.shape

(2, 5)

In [13]:
array2.shape

(2, 3, 5)

In [14]:
array.size

5

In [15]:
array1.size

10

In [16]:
array2.size

30

In [17]:
array2[1][0][2]

np.int64(33)

In [18]:
array1[1,2]

np.int64(8)

In [19]:
array2[1,0,3]

np.int64(44)

In [20]:
array1[1,1]*array3[1,2,3]

NameError: name 'array3' is not defined

In [ ]:
print(array1)     #vectorization/broadcasting
print("--------")
print(array1**2)

In [ ]:
print(array)
print("-------------")
print(array1)

In [ ]:
print(array*array1)

In [ ]:
np.sum(array)

In [ ]:
np.sum(array1)

In [ ]:
array3=np.zeros((3,5,4))

In [ ]:
print(array3)

In [ ]:
array4=np.ones((3,5,4))
print(array4)

In [ ]:
array5[1,2]=22

In [ ]:
print(array5)

In [ ]:
np.product(array3)

In [ ]:
array6=np.linspace(1,10,79)
print(array6)

In [ ]:
array2.size

In [21]:
array2.shape

(2, 3, 5)

In [22]:
array2.ndim

3

In [23]:
array6.ndim

NameError: name 'array6' is not defined

In [ ]:
array6.shape

In [24]:
array6.dtype

NameError: name 'array6' is not defined

In [25]:
list1 = [1, 2, 3, 4, 5]

arraylist = np.array(list1)
print(arraylist)

[1 2 3 4 5]


In [26]:
array1*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18,  0]])

In [27]:
array1[1]

array([6, 7, 8, 9, 0])

In [28]:
array1[1,2]

np.int64(8)

In [29]:
array1[1,2]*array3[1,1]

NameError: name 'array3' is not defined

In [ ]:
array1**2

In [30]:
#arrays contained same data type
#indexing, slicing

In [31]:
#list
list1=[33,44,55,66,69]

In [32]:
array1=np.array(list1)

In [33]:
array1

array([33, 44, 55, 66, 69])

In [34]:
list2=['king','queen',23,55,'rose','mary']

In [35]:
array8=np.array(list2)

In [36]:
array8

array(['king', 'queen', '23', '55', 'rose', 'mary'], dtype='<U21')

In [37]:
array8[2]

np.str_('23')

In [38]:
value=int(array8[2])

In [39]:
type(value)

int

In [40]:
try:
    value=int(input('Enter index:'))
    try:
        print(int(array8[value]))
    except ValueError:
        pass
except ValueError:
    value=array8[idx]
    print(value)
except IndexError:
    print('enetr prpoer index')

Enter index: 4


In [42]:
nums=[]
for i in list2:
    try:
        nums.append(float(i))
    except:
        pass

In [43]:
nums

[23.0, 55.0]

In [44]:
list3=['1e3','Nan','inf','3','4']

In [45]:
nums2=[]
for i in list3:
    try:
        nums.append(float(i))
    except:
        pass

In [46]:
nums

[23.0, 55.0, 1000.0, nan, inf, 3.0, 4.0]

In [47]:
nums3=[]

In [48]:
for i in list3:
    try:
        val=float(i)
        if not (val==float('1e3') or val==float('inf') or val==float('-inf') or val!=val):
            nums3.append(val)
    except:
        pass

In [49]:
nums3

[3.0, 4.0]

In [50]:
array9=np.array([1,2,3,4,5,6,7,8,9,11,22,33,44,55,66,77,88,99])

In [51]:
array9.size

18

In [52]:
array9.reshape(3,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11, 22, 33],
       [44, 55, 66, 77, 88, 99]])

In [53]:
array9.reshape(2,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]]])

In [54]:
array10=np.ones((5,7,9))

In [55]:
array10.reshape(35,9)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1.

In [56]:
array10.size

315

In [57]:
array10=np.resize(array7,50)

NameError: name 'array7' is not defined

In [58]:
array10

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.,

In [59]:
print(np.max(array(10))

_IncompleteInputError: incomplete input (2170280565.py, line 1)

In [60]:
print(np.argmax(array10))

0


In [61]:
array10.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [62]:
np.max(array10, axis=0)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [63]:
print(array2)

[[[11 22 33 44 55]
  [66 77 88 99  0]
  [11 33 55 77 99]]

 [[11 22 33 44 55]
  [66 77 88 99  0]
  [11 33 55 77 99]]]


In [64]:
np.sum(array2, axis=0)

array([[ 22,  44,  66,  88, 110],
       [132, 154, 176, 198,   0],
       [ 22,  66, 110, 154, 198]])

In [65]:
array11=np.ones(10)

In [66]:
array11

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [69]:
np.resize(array11,(50))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
expenses=np.array([
    [200,340,230,150,456],  #food
    [100,345,122,600,233],  #travel
    [350,450,256,800,654]   #shopping
])  

In [71]:
print('total expense: ',np.sum(expenses))
print('category wise sum: ',np.sum(expenses,axis=1))
print('day wise total: ',np.sum(expenses,axis=0))
print('highset expense day:',np.max(np.sum(expenses,axis=0)))


total expense:  5286
category wise sum:  [1376 1400 2510]
day wise total:  [ 650 1135  608 1550 1343]
highset expense day: 1550


In [86]:
marks=np.array([34,56,65,78,87,65,66])

In [87]:
grades = np.where(marks >= 75, "A",
          np.where(marks >= 55, "B",
          np.where(marks >= 45, "C", "FAIL")))
print(grades)

['FAIL' 'B' 'B' 'A' 'A' 'B' 'B']


In [88]:
grades = np.where(marks >= 75, "A",
          np.where(marks >= 60, "B",
          np.where(marks >= 45, "C", "FAIL")))

In [89]:
marks

array([34, 56, 65, 78, 87, 65, 66])

In [94]:
print(marks[(marks>60) & (marks>50)])

[65 78 87 65 66]


In [95]:
np.mean(marks)

np.float64(64.42857142857143)

In [97]:
np.median(marks)

np.float64(65.0)

In [99]:
np.std(marks)

np.float64(15.55503724436137)

In [100]:
check=np.ones(20)

In [109]:
np.std(check)

np.float64(677.9676172207637)

In [108]:
check[5]=3000

In [110]:
print(check)

[1.e+00 1.e+00 1.e+03 1.e+00 1.e+00 3.e+03 1.e+00 1.e+00 1.e+00 1.e+00
 1.e+00 1.e+00 1.e+00 1.e+00 1.e+00 1.e+00 1.e+00 1.e+00 1.e+00 1.e+00]


In [120]:
arr=np.array([1,2,3,4])

In [121]:
%timeit arr*2

1.39 μs ± 5.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [122]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [123]:
np.square(arr)

array([ 1,  4,  9, 16])

In [124]:
np.split(arr,2)

[array([1, 2]), array([3, 4])]